services:
  - type: web
    name: resolveit-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "False"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: resolveit-db
          property: connectionString
    disk:
      name: resolveit-disk
      mountPath: /opt/render/project/data
      sizeGB: 1
